# ----------------------------------- Diretório ------------------------------------
# Caminho do diretório lib e log:

path.data: /usr/share/elasticsearch/lib/
path.logs: /usr/share/elasticsearch/logs/

# ----------------------------------- Segurança ------------------------------------

discovery.type: single-node
xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true
bootstrap.memory_lock: true
ES_JAVA_OPTS: "-Xms512m -Xmx512m"