## Configuração

http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: ["http://192.168.1.110:9200"]

## Credenciais

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: tvk!2009